### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Tucanix** [maneac/go-ultralight#1]
Hello, when I try to build any of the examples I get this error:

```
# github.com/maneac/go-ultralight
/home/.tucanix/go/src/github.com/maneac/go-ultralight/SDK/bin/linux/libUltralightCore.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/home/.tucanix/go/src/github.com/maneac/go-ultralight/SDK/bin/linux/libUltralightCore.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/home/.tucanix/go/src/github.com/maneac/go-ultralight/SDK/bin/linux/libUltralightCore.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
collect2: error: ld returned 1 exit status­
```

**Version:**
go version go1.13.4 linux/amd64
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
Ubuntu 16.04.6 LTS

**Comment by prologic** [comment]
I'm running into this:

```#!sh
prologic@Jamess-MacBook
Mon Dec 23 13:15:31
~/Projects/ubrowser
 1
$ GOPROXY="" go build .
go build github.com/maneac/go-ultralight: invalid flag in #cgo LDFLAGS: -Wl,-rpath,.
```

**Comment by maneac** [comment]
> I'm running into this:
> 
> ```
> prologic@Jamess-MacBook
> Mon Dec 23 13:15:31
> ~/Projects/ubrowser
>  1
> $ GOPROXY="" go build .
> go build github.com/maneac/go-ultralight: invalid flag in #cgo LDFLAGS: -Wl,-rpath,.
> ```

This can be solved by enabling those flags in the environment:
`export CGO_LDFLAGS_ALLOW=.*`

You may also need to statically set the SDK binary path for correct detection:
`export LD_LIBRARY_PATH=$GOPATH/src/github.com/maneac/go-ultralight/SDK/bin/linux:$LD_LIBRARY_PATH`

**Comment by maneac** [comment]
> Hello, when I try to build any of the examples I get this error:
> 
> ```
> # github.com/maneac/go-ultralight
> /home/.tucanix/go/src/github.com/maneac/go-ultralight/SDK/bin/linux/libUltralightCore.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
> /home/.tucanix/go/src/github.com/maneac/go-ultralight/SDK/bin/linux/libUltralightCore.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
> /home/.tucanix/go/src/github.com/maneac/go-ultralight/SDK/bin/linux/libUltralightCore.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
> collect2: error: ld returned 1 exit status­
> ```
> 
> **Version:**
> go version go1.13.4 linux/amd64
> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
> Ubuntu 16.04.6 LTS

I can't be certain, but I believe the issue is due to an old version of GCC. Updating to GCC-8+ should work.

**Comment by prologic** [comment]
> > I'm running into this:
> > ```
> > prologic@Jamess-MacBook
> > Mon Dec 23 13:15:31
> > ~/Projects/ubrowser
> >  1
> > $ GOPROXY="" go build .
> > go build github.com/maneac/go-ultralight: invalid flag in #cgo LDFLAGS: -Wl,-rpath,.
> > ```
> 
> This can be solved by enabling those flags in the environment:
> `export CGO_LDFLAGS_ALLOW=.*`
> 
> You may also need to statically set the SDK binary path for correct detection:
> `export LD_LIBRARY_PATH=$GOPATH/src/github.com/maneac/go-ultralight/SDK/bin/linux:$LD_LIBRARY_PATH`

This helped a little bit but now I get:

```sh
prologic@Jamess-MacBook
Wed Jan 22 21:53:42
~/Projects/ubrowser
 0
$ CGO_CFLAGS="-I /Users/prologic/tmp/ultralight/include" go build
# github.com/raff/ultralight-go
../../go/pkg/mod/github.com/raff/ultralight-go@v0.0.0-20190620222822-d2efebcfd598/ultralight.go:378:50: could not determine kind of name for C.kWindowFlags_Maximizable
../../go/pkg/mod/github.com/raff/ultralight-go@v0.0.0-20190620222822-d2efebcfd598/ultralight.go:378:25: could not determine kind of name for C.kWindowFlags_Resizable
../../go/pkg/mod/github.com/raff/ultralight-go@v0.0.0-20190620222822-d2efebcfd598/ultralight.go:378:3: could not determine kind of name for C.kWindowFlags_Titled
```

I don't know what any of this means at the moment... But I'll keep poking around...

**Comment by maneac** [comment]
The later issues are due to an update method signature in the v1.1 SDK. A patch is coming shortly
