### ISSUE TITLE
Feature Request - Add LoadFile method

### ISSUE THREAD

**Issue by felipetesc** [maneac/go-ultralight#2]
Hello. I've written this message to ask if we can add a method called LoadFile. It could be something like this:

```
func (view *View) LoadHTML(path string) {
	htmlFile, err := os.Open(path)
	if err != nil {
		log.Fatal(err)
	}
	defer htmlFile.Close()

	bytes := new(bytes.Buffer)
	bytes.ReadFrom(htmlFile)
	contents := buf.String()
	C.ulViewLoadHTML(view.v, C.ulCreateString(C.CString(contents)))
}
```

And thanks for creating this project.

**Comment by maneac** [comment]
Hey, thanks for your suggestion. This project aims to mirror the original developer API as closely as possible, and was originally intended for use by those already familiar with the Ultralight project.

I do intend to create another library on top of this, adding some creature comforts and additional functionality such as this, so keep your eyes peeled!
