### ISSUE TITLE
Calling go Functions from JS

### ISSUE THREAD

**Issue by Gurkengewuerz** [maneac/go-ultralight#3]
Hey,

i really like your go bindings for ultralight. I tested lorca and webview and ultralight is according to my tests, the best. Is it possible to return a JSValue to get the result in javascript?
The [ultralight-ux/Ultralight/wiki/JavaScript-Integration](https://github.com/ultralight-ux/Ultralight/wiki/JavaScript-Integration#calling-c-functions-from-js)  says it should work using the c library.

Thanks for your answer :))

**Comment by maneac** [comment]
Hi,

Thanks for your feedback! Following the latest update, returning values from Go to JavaScript is now supported, with an example demonstrating their use.

**Comment by Gurkengewuerz** [comment]
Wow. Thank you for your efforts. Works great!
